# Generated by Django 4.2.9 on 2024-01-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='donor_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='people',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
