# Generated by Django 4.2.9 on 2024-01-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contribution_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='people',
            field=models.IntegerField(null=True),
        ),
    ]
