# Generated by Django 4.2.9 on 2024-01-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contribution_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='donor_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='people',
            field=models.IntegerField(default=10),
        ),
    ]
