# Generated by Django 4.2.9 on 2024-02-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contribution_requests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-people']},
        ),
    ]
